DROP TABLE dbo.MSCP;
DROP TABLE dbo.ParkingLots;
DROP TABLE dbo.ShortTermRate;
DROP TABLE dbo.Email;
DROP TABLE dbo.ContactNumber;
DROP TABLE dbo.R_SeasonPass_2;
DROP TABLE dbo.R_Transaction_SeasonPass_1;
DROP TABLE dbo.Tx_ShortTermParking;
DROP TABLE dbo.Offence;
DROP TABLE dbo.Rules;
DROP TABLE dbo.ParkingRecord;
DROP TABLE dbo.Vehicle1;
DROP TABLE dbo.VehicleModel;
DROP TABLE dbo.Owner;
DROP TABLE dbo.ParkingModeRecord;
DROP TABLE dbo.ResidentUnit;
DROP TABLE dbo.BlockAddress
DROP TABLE dbo.NormalCarpark;
DROP TRIGGER BuySimulation;
